# Auto-generated by the terragrunt.stack.hcl file by Terragrunt. Do not edit manually
gke_pods_secondary_range_cidr     = "10.68.0.0/14"
gke_services_secondary_range_cidr = "10.72.0.0/20"
vpc_cidr_prefix                   = "10.64"
