# Auto-generated by the terragrunt.stack.hcl file by Terragrunt. Do not edit manually
custom_images = {
  envoy  = "REPLACE_ME-envoy"
  socks5 = "REPLACE_ME-socks5"
  squid  = "REPLACE_ME-squid"
}
domains = {
  api     = "api.sandbox.example.com"
  grafana = "grafana.sandbox.example.com"
}
