# Auto-generated by the terragrunt.stack.hcl file by Terragrunt. Do not edit manually
custom_images = {
  envoy = "REPLACE_ME-envoy"
  squid = "REPLACE_ME-squid"
}
gke_pods_secondary_range_cidr = "10.68.0.0/14"
vpc_cidr_prefix               = "10.64"
