# Auto-generated by the terragrunt.stack.hcl file by Terragrunt. Do not edit manually
domains = {
  api     = "api.sandbox.example.com"
  grafana = "grafana.sandbox.example.com"
}
smtp_secret_id = null
