# Auto-generated by the terragrunt.stack.hcl file by Terragrunt. Do not edit manually
custom_images = {
  envoy = "hyperswitch-envoy-dev-20260820032919"
  squid = "family/hyperswitch-squid-dev"
}
gke_pods_secondary_range_cidr = "10.100.0.0/16"
vpc_cidr_prefix               = "10.2"
