# Auto-generated by the terragrunt.stack.hcl file by Terragrunt. Do not edit manually
locker = {
  availability_type    = "ZONAL"
  cpu_count            = 2
  deletion_protection  = false
  kms_protection_level = "SOFTWARE"
}
