# Auto-generated by the terragrunt.stack.hcl file by Terragrunt. Do not edit manually
alert_notification_email = "REPLACE_ME@example.com"
bastion_iap_members      = ["group:REPLACE_ME@example.com"]
custom_images = {
  cassandra         = "REPLACE_ME-cassandra"
  clickhouse_keeper = "REPLACE_ME-clickhouse-keeper"
  clickhouse_server = "REPLACE_ME-clickhouse-server"
  envoy             = "REPLACE_ME-envoy"
  kafka_broker      = "REPLACE_ME-kafka-broker"
  kafka_controller  = "REPLACE_ME-kafka-controller"
  locker            = "REPLACE_ME-locker"
  opensearch        = "REPLACE_ME-opensearch"
  squid             = "REPLACE_ME-squid"
}
domains = {
  api     = "api.sandbox.example.com"
  grafana = "grafana.sandbox.example.com"
}
env                               = "sandbox"
gke_pods_secondary_range_cidr     = "10.68.0.0/14"
gke_services_secondary_range_cidr = "10.72.0.0/20"
machine_types = {
  bastion             = "e2-small"
  gke_generic_compute = "e2-standard-4"
  gke_system_pool     = "e2-standard-4"
}
project_id      = "REPLACE_ME-gcp-project"
region          = "asia-south1"
smtp_secret_id  = null
state_bucket    = "REPLACE_ME-sandbox-asia-south1-tfstate"
vpc_cidr_prefix = "10.64"
vpn_cidr_blocks = []
