# Auto-generated by the terragrunt.stack.hcl file by Terragrunt. Do not edit manually
alloydb = {
  availability_type   = "ZONAL"
  cpu_count           = 2
  deletion_protection = true
  read_pool_instances = {}
}
domains = {
  api     = "api.sandbox.example.com"
  grafana = "grafana.sandbox.example.com"
}
env                               = "sandbox"
gke_pods_secondary_range_cidr     = "10.68.0.0/14"
gke_services_secondary_range_cidr = "10.72.0.0/20"
machine_types = {
  gke_generic_compute = "e2-standard-4"
  gke_system_pool     = "e2-standard-4"
}
project_id     = "REPLACE_ME-gcp-project"
region         = "asia-south1"
smtp_secret_id = null
state_bucket   = "REPLACE_ME-sandbox-asia-south1-tfstate"
valkey = {
  deletion_protection_enabled = true
  node_type                   = "SHARED_CORE_NANO"
  replica_count               = 1
  shard_count                 = 1
}
vpc_cidr_prefix = "10.64"
vpn_cidr_blocks = []
