# Auto-generated by the terragrunt.stack.hcl file by Terragrunt. Do not edit manually
valkey = {
  deletion_protection_enabled = true
  node_type                   = "SHARED_CORE_NANO"
  replica_count               = 1
  shard_count                 = 1
}
