# Auto-generated by the terragrunt.stack.hcl file by Terragrunt. Do not edit manually
alloydb = {
  availability_type   = "ZONAL"
  cpu_count           = 2
  deletion_protection = false
  read_pool_instances = {}
}
