# Auto-generated by the terragrunt.stack.hcl file by Terragrunt. Do not edit manually
ami_id      = "ami-REPLACE_ME"
base_domain = "dev.example.com"
virtual_hosts_domains = {
  api = ["api.dev.example.com"]
}
