# shellcheck shell=bash
# Config persistence: hyperswitch-bootstrap.conf in the merchant repo root.
# Format: KEY="VALUE" lines, sourced back in as prompt defaults on rerun.
# Secrets must never be added to CONFIG_KEYS.

CONFIG_FILE_NAME="hyperswitch-bootstrap.conf"

# Every prompted key, in prompt order. Derived keys are computed, not listed.
CONFIG_KEYS=(
    MERCHANT_NAME
    MERCHANT_REPO_URL
    ENVIRONMENT
    AWS_ACCOUNT_ID
    AWS_REGION
    STATE_BUCKET
    VPC_ID
    VPC_CIDR
    DB_SUBNET_IDS
    CACHE_SUBNET_IDS
    EKS_WORKER_SUBNET_IDS
    EKS_CP_SUBNET_IDS
    PUBLIC_SUBNET_IDS
    ADMIN_ROLE_ARN
    ADMIN_ACCESS_CIDRS
    ACM_CERT_ARN
    ROUTER_DOMAIN
    SDK_DOMAIN
    CONTROL_CENTER_DOMAIN
    DB_INSTANCE_CLASS
    DB_ENGINE_VERSION
    CACHE_NODE_TYPE
    EKS_VERSION
    EKS_INSTANCE_TYPES
    EKS_AMI_ID
    IMAGE_REGISTRY
    HS_CHART_VERSION
    TFSTATE_PLUGIN_IMAGE
    ENABLE_KARPENTER
    ENABLE_ESO
    ENABLE_CONTROL_CENTER
)

load_config() {
    local config_file="$1"
    [[ -f "$config_file" ]] || return 0
    info "Loading saved answers from ${config_file}"
    # shellcheck disable=SC1090
    source "$config_file"
}

save_config() {
    local config_file="$1" key
    {
        echo "# Generated by scripts/self-host/generate.sh"
        echo "# Rerun generate.sh in this repo to regenerate with these answers as defaults."
        echo "# Never put secrets in this file."
        for key in "${CONFIG_KEYS[@]}"; do
            printf '%s="%s"\n' "$key" "${!key:-}"
        done
    } >"$config_file"
    ok "Saved answers to ${config_file}"
}
