# Auto-generated by the terragrunt.stack.hcl file by Terragrunt. Do not edit manually
account_id                   = "000000000000"
admin_access_cidrs           = []
admin_role_arn               = "arn:aws:iam::000000000000:role/REPLACE_ME"
ami_id                       = "ami-REPLACE_ME"
base_domain                  = "dev.example.com"
cache_node_type              = "cache.m6g.large"
db_engine_version            = "17.9"
db_instance_class            = "db.r5.large"
eks_ami_id                   = null
eks_instance_types           = ["t3.xlarge"]
eks_version                  = "1.35"
env                          = "dev"
generic_compute_desired_size = 2
generic_compute_min_size     = 1
istio_host_domains = {
  dev = "istio.internal.staging.euc1.dev.example.com"
}
project_name              = "hyperswitch"
region                    = "eu-central-1"
region_code               = "euc1"
state_bucket              = "hyperswitch-tfstate-dev"
system_nodes_desired_size = 1
virtual_hosts_domains = {
  api = ["api.dev.example.com"]
}
vpc_cidr_prefix = "10.10"
