{{- range .Values.serviceEntries }}
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/part-of: istio
spec:
  hosts:
  {{- range .hosts }}
    - {{ . | quote }}
  {{- end }}
  {{- with .addresses }}
  addresses:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  ports:
  {{- range .ports }}
    - number: {{ .number }}
      name: {{ .name }}
      protocol: {{ .protocol }}
      {{- with .targetPort }}
      targetPort: {{ . }}
      {{- end }}
  {{- end }}
  location: {{ .location | default "MESH_EXTERNAL" }}
  resolution: {{ .resolution | default "DNS" }}
  {{- with .endpoints }}
  endpoints:
  {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
