# Auto-generated by the terragrunt.stack.hcl file by Terragrunt. Do not edit manually
admin_access_cidrs = []
admin_sso_role_arn = "arn:aws:iam::000000000000:role/REPLACE_ME"
cluster_version    = "1.35"
default_ami_id     = null
generic_compute = {
  desired_size   = 2
  instance_types = ["t3.xlarge"]
  min_size       = 1
}
system_nodes = {
  desired_size   = 1
  instance_types = ["t3.xlarge"]
}
