# Auto-generated by the terragrunt.stack.hcl file by Terragrunt. Do not edit manually
custom_images = {
  cassandra         = "REPLACE_ME-cassandra"
  clickhouse_keeper = "REPLACE_ME-clickhouse-keeper"
  clickhouse_server = "REPLACE_ME-clickhouse-server"
  envoy             = "REPLACE_ME-envoy"
  kafka_broker      = "REPLACE_ME-kafka-broker"
  kafka_controller  = "REPLACE_ME-kafka-controller"
  locker            = "REPLACE_ME-locker"
  opensearch        = "REPLACE_ME-opensearch"
  squid             = "REPLACE_ME-squid"
}
