# Auto-generated by the terragrunt.stack.hcl file by Terragrunt. Do not edit manually
gke_pods_secondary_range_cidr     = "10.100.0.0/16"
gke_services_secondary_range_cidr = "10.101.0.0/20"
network_options = {
  enable_default_deny_egress  = true
  enable_default_deny_ingress = true
  enable_psc_google_apis      = true
  nat_log_filter              = "ALL"
  nat_subnetwork_tiers        = ["outgoing-proxy"]
  network_name                = "hyperswitch-dev-vpc"
  vpc_internal_ranges = {
    gke_pods = "10.100.0.0/16"
    gke_svcs = "10.101.0.0/20"
    primary  = "10.2.0.0/16"
    psa      = "10.214.0.0/16"
  }
}
subnet_cidrs = {
  data_stack           = "10.2.80.0/24"
  database             = "10.2.73.0/24"
  external_incoming    = "10.2.64.0/24"
  gke_nodes            = "10.2.32.0/20"
  locker_database      = "10.2.75.0/24"
  locker_server        = "10.2.76.0/24"
  management           = "10.2.67.0/24"
  memorystore          = "10.2.74.0/24"
  outgoing_proxy       = "10.2.77.0/24"
  serverless_connector = "10.2.90.0/28"
}
vpc_cidr_prefix = "10.2"
