# Auto-generated by the terragrunt.stack.hcl file by Terragrunt. Do not edit manually
custom_images = {
  envoy = "hyperswitch-envoy-dev-20260820032919"
  squid = "family/hyperswitch-squid-dev"
}
domains = {
  api     = "dev.hyperswitch.internal"
  grafana = "dev.hyperswitch.internal"
}
