# Auto-generated by the terragrunt.stack.hcl file by Terragrunt. Do not edit manually
gke_deletion_protection    = false
gke_master_ipv4_cidr_block = "172.16.0.0/28"
machine_types = {
  bastion             = "e2-small"
  gke_generic_compute = "e2-standard-2"
  gke_system_pool     = "e2-standard-2"
}
