# Auto-generated by the terragrunt.stack.hcl file by Terragrunt. Do not edit manually
machine_types = {
  bastion             = "e2-small"
  gke_generic_compute = "e2-standard-4"
  gke_system_pool     = "e2-standard-4"
}
