# Auto-generated by the terragrunt.stack.hcl file by Terragrunt. Do not edit manually
alloydb = {
  availability_type   = "ZONAL"
  cpu_count           = 2
  deletion_protection = false
  read_pool_instances = {}
}
bastion_iap_members = ["group:platform-team@example.com"]
custom_images = {
  envoy = "hyperswitch-envoy-dev-20260820032919"
  squid = "family/hyperswitch-squid-dev"
}
domains = {
  api     = "dev.hyperswitch.internal"
  grafana = "dev.hyperswitch.internal"
}
env                               = "dev"
gke_deletion_protection           = false
gke_master_ipv4_cidr_block        = "172.16.0.0/28"
gke_pods_secondary_range_cidr     = "10.100.0.0/16"
gke_services_secondary_range_cidr = "10.101.0.0/20"
locker = {
  availability_type    = "ZONAL"
  cpu_count            = 2
  deletion_protection  = false
  kms_protection_level = "SOFTWARE"
}
machine_types = {
  bastion             = "e2-small"
  gke_generic_compute = "e2-standard-2"
  gke_system_pool     = "e2-standard-2"
}
network_options = {
  enable_default_deny_egress  = true
  enable_default_deny_ingress = true
  enable_psc_google_apis      = true
  nat_log_filter              = "ALL"
  nat_subnetwork_tiers        = ["outgoing-proxy"]
  network_name                = "hyperswitch-dev-vpc"
  vpc_internal_ranges = {
    gke_pods = "10.100.0.0/16"
    gke_svcs = "10.101.0.0/20"
    primary  = "10.2.0.0/16"
    psa      = "10.214.0.0/16"
  }
}
project_id           = "hyperswitch-dev"
project_name         = "hyperswitch"
region               = "asia-south1"
skip_bucket_creation = false
smtp_secret_id       = null
state_bucket         = "hyperswitch-dev-asia-south1-terraform-state"
subnet_cidrs = {
  data_stack           = "10.2.80.0/24"
  database             = "10.2.73.0/24"
  external_incoming    = "10.2.64.0/24"
  gke_nodes            = "10.2.32.0/20"
  locker_database      = "10.2.75.0/24"
  locker_server        = "10.2.76.0/24"
  management           = "10.2.67.0/24"
  memorystore          = "10.2.74.0/24"
  outgoing_proxy       = "10.2.77.0/24"
  serverless_connector = "10.2.90.0/28"
}
valkey = {
  deletion_protection_enabled = false
  node_type                   = "SHARED_CORE_NANO"
  replica_count               = 1
  shard_count                 = 1
}
vpc_cidr_prefix = "10.2"
vpn_cidr_blocks = [{
  cidr_block   = "198.51.100.0/30"
  display_name = "office"
  }, {
  cidr_block   = "203.0.113.10/32"
  display_name = "vpn"
  }, {
  cidr_block   = "10.2.67.0/24"
  display_name = "management-subnet-bastion"
}]
