# Auto-generated by the terragrunt.stack.hcl file by Terragrunt. Do not edit manually
alloydb = {
  availability_type   = "ZONAL"
  cpu_count           = 2
  deletion_protection = false
  read_pool_instances = {}
}
bastion_iap_members = ["group:REPLACE_ME@example.com"]
custom_images = {
  envoy = "REPLACE_ME-envoy"
  squid = "REPLACE_ME-squid"
}
domains = {
  api     = "api.dev.example.com"
  grafana = "grafana.dev.example.com"
}
env                               = "dev"
gke_pods_secondary_range_cidr     = "10.100.0.0/16"
gke_services_secondary_range_cidr = "10.101.0.0/20"
locker = {
  availability_type    = "ZONAL"
  cpu_count            = 2
  deletion_protection  = false
  kms_protection_level = "SOFTWARE"
}
machine_types = {
  bastion             = "e2-small"
  gke_generic_compute = "e2-standard-4"
  gke_system_pool     = "e2-standard-4"
}
project_id     = "REPLACE_ME-gcp-project"
region         = "asia-south1"
smtp_secret_id = null
state_bucket   = "REPLACE_ME-dev-asia-south1-tfstate"
valkey = {
  deletion_protection_enabled = false
  node_type                   = "SHARED_CORE_NANO"
  replica_count               = 1
  shard_count                 = 1
}
vpc_cidr_prefix = "10.2"
vpn_cidr_blocks = []
