cache deny all

acl SSL_ports port 443
acl SSL_ports port 80
acl CONNECT method CONNECT
http_access deny CONNECT !SSL_ports

acl allowed_sites_domain dstdomain "/etc/squid/squid.allowed.sites.txt"
acl allowed_sites_ip dst 203.0.113.6
http_access allow allowed_sites_domain
http_access allow allowed_sites_ip

http_access deny all

http_port 0.0.0.0:3128

coredump_dir /var/spool/squid
