# Auto-generated by the terragrunt.stack.hcl file by Terragrunt. Do not edit manually
bastion_iap_members = ["group:platform-team@example.com"]
machine_types = {
  bastion             = "e2-small"
  gke_generic_compute = "e2-standard-2"
  gke_system_pool     = "e2-standard-2"
}
